---
# tasks file for geekoops-mysql

- name: Get mysql8 community repos
  get_url:
    url: https://repo.mysql.com/mysql80-community-release-sl15-6.noarch.rpm
    dest: /tmp/
- name: Add mysql8 community repos
  zypper:
    name: '/tmp/mysql80-community-release-sl15-6.noarch.rpm'
    disable_gpg_check: yes
    state: latest
- name: install mysql8 from community repos
  package:
    name: mysql-community-server
    disable_gpg_check: yes
    update_cache: yes
    state: latest
- name: Ensure mysql settings are up-to-date
  template:
    dest: /etc/my.cnf
    src: my.cnf
- name: Start and enable systemd service for mysql
  systemd:
    name: mysql
    state: started

## Apply temporary password for root user ######################################

- name: Check for root user configuration
  stat:
    path: /root/.my.cnf
  register: root_my_cnf
- name: Get mysql temporary password
  command: awk '/password/{print $NF}' /var/log/mysql/mysqld.log
  register: sqlpassword
  when: not root_my_cnf.stat.exists
- name: Add temporary password to the root user configuration
  template:
    src: root_my.cnf
    dest: /root/.my.cnf
  when: not root_my_cnf.stat.exists
- name: Make temporary password permanent
  command: mysqladmin password "{{ sqlpassword.stdout }}"
  when: not root_my_cnf.stat.exists
- name: Restart mysql service
  systemd:
    name: mysql
    state: restarted
  when: not root_my_cnf.stat.exists
